CREATE TABLE "walls_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "walls_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "walls_file" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "walls_file_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"base64" text NOT NULL,
	"uploaded_by" varchar(255) NOT NULL,
	"uploaded_at" timestamp DEFAULT now() NOT NULL,
	"height" integer NOT NULL,
	"width" integer NOT NULL,
	"size" integer NOT NULL,
	"nsfw" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "walls_file_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "walls_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "walls_settings" (
	"user_id" varchar(255) PRIMARY KEY NOT NULL,
	"redirect_to_my_wall" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "walls_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"joined_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "walls_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "walls_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "walls_account" ADD CONSTRAINT "walls_account_user_id_walls_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."walls_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "walls_file" ADD CONSTRAINT "walls_file_uploaded_by_walls_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."walls_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "walls_session" ADD CONSTRAINT "walls_session_user_id_walls_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."walls_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "walls_settings" ADD CONSTRAINT "walls_settings_user_id_walls_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."walls_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "walls_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "walls_session" USING btree ("user_id");