CREATE TABLE "walls_app_settings" (
	"key" varchar(255) PRIMARY KEY NOT NULL,
	"value" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "walls_invite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "walls_invite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"invited_by" varchar(255) NOT NULL,
	"invited_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "walls_invite_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "walls_user" ADD COLUMN "blocked" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "walls_invite" ADD CONSTRAINT "walls_invite_invited_by_walls_user_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."walls_user"("id") ON DELETE no action ON UPDATE no action;