CREATE TABLE "walls_invite_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "walls_invite_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"requested_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "walls_invite_request_email_unique" UNIQUE("email")
);
