name: test linting
on:
  push:
  pull_request:

jobs:
  test-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - run: bun i --frozen-lockfile
      - run: bun run lint
