name: pull request
on:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker build --target app -t website .

  docker-build-migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker build --target migrate -t website-migrate .

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run format:check

  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
