name: push on main branch
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t website .

  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run format:check

  test-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build

  build-push:
    needs:
      - test-docker-build
      - test-formatting
      - test-npm-build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/walls/website:latest .
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: acr login
        run: az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}
      - name: push image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/walls/website:latest
